language: c
sudo: false
dist: xenial
env:
  global:
    - PATH=~/.roswell/bin:~/.linuxbrew/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - ROSWELL_QUICKLISP_DIST_URI=https://github.com/roswell/quicklisp/releases/download/dist/quicklisp.txt
    - LISP=sbcl-bin
  matrix:
    - TEST_SYSTEM=yaclml/test:yadd:yason:zacl:zaserve:zaws:zaws-xml:zcdb:zenekindarl:zenekindarl-test:zeromq:zeromq.tests:zip:zlib:zmq:zmq-examples:zmq-test:zpb-exif:zpb-ttf:zpng:zs3:zsort

os:
  - osx
  - linux


script:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - ros system-build.ros
